apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    concurrency: 1
    useDockerCLI: true
    push: false
  artifacts:
    - image: afif1400/image-service
      context: image-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/***/*'
