apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-manager-depl
spec:
  selector:
    matchLabels:
      app: image-manager
  template:
    metadata:
      labels:
        app: image-manager
    spec:
      containers:
      - name: image-manager
        image: afif1400/image-service
        resources:
          limits:
            memory: "500Mi"
            cpu: "600m"
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: docker-socket

---
apiVersion: v1
kind: Service
metadata:
  name: image-manager-srv
spec:
  selector:
    app: image-manager
  ports:
    - name: image-manager
      protocol: TCP
      port: 5000
      targetPort: 5000
